# Load secrets from Key Vault

#variables:
#  - group: e2e-gov-demo-kv


trigger: 
- main

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  projectRoot: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    
    steps:
    
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Azure subscription 1(efa42e01-27ef-4660-b3e7-2f62a24bd429)'
        KeyVaultName: 'falace-kv'
        SecretsFilter: '*'
        RunAsPreJob: true

    - bash: ls
      workingDirectory: $(projectRoot)
      displayName: Listing

    - bash: echo $TEST_VARIABLE
      workingDirectory: $(projectRoot)
      displayName: Listing
      env:
        TEST_VARIABLE: $(TEST_VARIABLE)

    #- bash: source ./terraform/create_azure_storage.sh
    #  workingDirectory: $(projectRoot)
    #  displayName: Creating Storage

    - bash: |
        cd terraform && terraform init \
          -backend-config="resource_group_name=$RESOURCE_GROUP_NAME" \
          -backend-config="storage_account_name=$STORAGE_ACCOUNT_NAME" \
          -backend-config="container_name=$CONTAINER_NAME" \
          -backend-config="access_key=$ARM_ACCESS_KEY"
      displayName: Terraform Init
      
      # sensitive data, will rotate once it works.
      env:
        ARM_SUBSCRIPTION_ID: $(falace-kv-subscription-id)
        ARM_CLIENT_ID:       $(falace-kv-client-id)
        ARM_CLIENT_SECRET:   $(falace-kv-client-secret)
        ARM_TENANT_ID:       $(falace-kv-tenant-id)
        ARM_ACCESS_KEY:      $(falace-kv-access-key)
      
      #env:
        #TF_STATE_BLOB_ACCOUNT_NAME:   $(kv-tf-state-blob-account)
        #TF_STATE_BLOB_CONTAINER_NAME: $(kv-tf-state-blob-container)
        #TF_STATE_BLOB_FILE:           $(kv-tf-state-blob-file)
        #TF_STATE_BLOB_SAS_TOKEN:      $(kv-tf-state-sas-token)
