# Load secrets from Key Vault

#variables:
#  - group: e2e-gov-demo-kv


trigger: 
- main

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  projectRoot: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    
    steps:
    
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Azure subscription 1(efa42e01-27ef-4660-b3e7-2f62a24bd429)'
        KeyVaultName: 'falace-kv'
        SecretsFilter: '*'
        RunAsPreJob: true

    - bash: ls
      workingDirectory: $(projectRoot)
      displayName: Listing
    
    - bash: |
        printenv
      displayName: Print Env
      env:
        ARM_SUBSCRIPTION_ID: $(subscription-id)
        ARM_CLIENT_ID:       $(client-id)
        ARM_CLIENT_SECRET:   $(client-secret)
        ARM_TENANT_ID:       $(tenant-id)
        ARM_ACCESS_KEY:      $(access-key)
        TF_RESOURCE_GROUP: $(resource-group)
        TF_ACCOUNT_NAME:   $(account-name)
        TF_CONTAINER_NAME: $(container-name)
        TF_KEY:           $(key)